modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="deterministic_chance"
version="${version}"
displayName="确定的概率"
authors="LangQi99"
description='''
把概率产出转换为可预测的确定序列，并为 AE2 批量处理样板提供精确产物计划。
'''

[[dependencies.deterministic_chance]]
modId="forge"
mandatory=true
versionRange="[47.4.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="mekanism"
mandatory=false
versionRange="[10.4.16,10.5)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="ae2"
mandatory=false
versionRange="[15.4.10,16)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="jei"
mandatory=false
versionRange="[15.49,16)"
ordering="AFTER"
side="CLIENT"

[[dependencies.deterministic_chance]]
modId="create"
mandatory=false
versionRange="[6.0.0,6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="thermal"
mandatory=false
versionRange="[11.0.0,11.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="thermal_expansion"
mandatory=false
versionRange="[11.0.0,11.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="thermal_foundation"
mandatory=false
versionRange="[11.0.0,11.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="gtceu"
mandatory=false
versionRange="[7.0.0,8.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.deterministic_chance]]
modId="immersiveengineering"
mandatory=false
versionRange="[1.20.1-10.2.0-183]"
ordering="AFTER"
side="BOTH"
